export const aboutMe = `
I'm Isfaqul. Self-taught full-stack developer focused on [TypeScript](https://www.typescriptlang.org/) and [React](https://react.dev/). Learning by building, breaking, and improving every day.

This blog is a place where I write about what I’m learning, the problems I run into, and the small insights that come from working through them. I care about understanding how things actually work—not just making them work.

Learning hasn’t always been smooth, but I try to stay consistent and improve a little every day. Writing helps me slow down, think clearly, and track that progress over time.

I’m still learning. This is part of that journey.
`;

export const aboutThisPage = `
Everything you see here I have designed and built myself. The website is using [React](https://react.dev/) and [Tailwind](https://tailwindcss.com/). The pages are generated by [React Router](https://reactrouter.com/) and are hosted on [Netlify](https://www.netlify.com/).
`;

export const likes = [
  "Minimal Design",
  "Photography",
  "Japan Culture",
  "Cooking",
  "Pizza",
  "Ramen",
  "New Gadgets",
  "Continuous Learning",
  "Bikerides",
  "Stand-up Comedy",
];

export const dislikes = [
  "Bad Design",
  "Lies & Liers",
  "Podcasts",
  "Ads",
  "Politics",
  "Unclear Requirements",
  "Tea",
  "Notifications",
];
