import Heading from "../components/Heading";

export default function About() {
  return (
    <>
      <section>
        <hgroup className="flex justify-between items-baseline mb-6">
          <Heading level={1} className="heading-b-border">
            About me
          </Heading>
        </hgroup>
        <div className="space-y-6">
          <p className="font-body text-tGray-100 text-xl font-light">
            I'm Isfaqul. Self-taught full-stack developer focused on JavaScript and React. Learning by building,
            breaking, and improving every day.
          </p>
          <p className="font-body text-tGray-100 text-xl font-light">
            This blog is a place where I write about what I’m learning, the problems I run into, and the small insights
            that come from working through them. I care about understanding how things actually work—not just making
            them work.
          </p>
          <p className="font-body text-tGray-100 text-xl font-light">
            Learning hasn’t always been smooth, but I try to stay consistent and improve a little every day. Writing
            helps me slow down, think clearly, and track that progress over time.
          </p>
          <p className="font-body text-tGray-100 text-xl font-light">
            I’m still learning. This is part of that journey.
          </p>
        </div>
      </section>
      <section className="my-16">
        <hgroup className="flex justify-between items-baseline mb-6">
          <Heading level={2} size="text-2xl" className="heading-b-border">
            About this page
          </Heading>
        </hgroup>
        <div className="space-y-6">
          <p className="font-body text-tGray-100 text-xl font-light">
            Everything you see here I have designed and built myself. The website is using React and Tailwind. The pages
            are generated by ReactRouter and are hosted on Netlify.
          </p>
          <p className="font-body text-tGray-100 text-xl font-light">
            The content for the website, such as articles, books and bookmarks are stored on Airtable and then pulled in
            through their API endpoint. If you are curious, you can explore the code for this website on my Github.
          </p>
        </div>
      </section>
    </>
  );
}
